# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'Stipend' do

pod 'AFNetworking', '~> 3.0'
pod 'SDWebImage', '3.7.2'
pod 'FBSDKShareKit'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'SVProgressHUD', '1.1.3'
pod 'MagicalRecord', '2.3.2'
pod 'Fabric'
pod 'Crashlytics'
pod 'TwitterKit'
pod 'TwitterCore'
pod 'Firebase/Core'

end

target 'StipendTests' do

end

